model_params:
  name: 'BetaVAE_MultiCLF'
  in_channels: 1
  latent_dim: 5
  loss_type: 'B'
  beta: 3
  gamma: 5000.0
  max_capacity: 1
  Capacity_max_iter: 2500 #10000
  task_list: [0,1,2,3]

data_params:
  data_path: "data/mazes_200k_2corridors_13x13.csv"
  num_labels: 2
  train_val_test_split: [170000, 185000]
  train_batch_size: 64
  val_batch_size:  32
  test_batch_size: 32
  patch_size: 32
  num_workers: 4
  
exp_params:
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.9
  kld_weight: 0.0003
  manual_seed: 0 #1265

trainer_params:
  accelerator: "gpu"
  devices: [0,1]
  max_epochs: 6

logging_params:
  save_dir: "logs/"
  manual_seed: 0 #1265
  name: 'BetaVAE_MultiCLF'
