model_params:
  name: 'BetaVAE_CLF'
  in_channels: 1
  latent_dim: 5
  loss_type: 'B'
  gamma: 100.0
  beta: 10
  max_capacity: 5
  Capacity_max_iter: 4000 #10000
  hidden_dims: [64, 128, 256, 512]

data_params:
  data_path: "data/mazes_200k_2corridors_13x13.csv"
  num_labels: 2
  train_val_test_split: [170000, 185000]
  train_batch_size: 64
  val_batch_size:  32
  test_batch_size: 32
  patch_size: 32
  num_workers: 4
  
exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 0 #1265

trainer_params:
  accelerator: "gpu"
  gpus: [0,1]
  max_epochs: 5

logging_params:
  save_dir: "logs/"
  manual_seed: 0 #1265
  name: 'BetaVAE_CLF'
