model_params:
  name: 'BetaVAE_MLP_CLF'
  in_channels: 1
  latent_dim: 5
  loss_type: 'H'
  beta: 200
  gamma: 20.0
  max_capacity: 10
  Capacity_max_iter: 10000
  hidden_dims: []

data_params:
  data_path: "data/mazes_2gf_discrete_big_relabelled.csv"
  train_batch_size: 512
  val_batch_size:  64
  test_batch_size: 64
  patch_size: 32
  num_workers: 4
  
exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: "gpu"
  gpus: [0,1]
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  manual_seed: 1265
  name: 'BetaVAE_MLP_CLF'
