model_params:
  name: 'BetaVAE'
  in_channels: 1
  latent_dim: 1
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000
  hidden_dims: [64, 128, 256, 512]

data_params:
  data_path: "data/maze_small_gaussian.csv"
  train_batch_size: 64
  val_batch_size:  32
  test_batch_size: 32
  patch_size: 32
  num_workers: 4
  
exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: "gpu"
  gpus: [0,1]
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  manual_seed: 1265
  name: 'BetaVAE'
